<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
    <ItemGroup>
        <Reference Include="$(ElinWorkshopPath)\3379819704\ModConfigGUI.dll">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>